<?php
    $xmlr = file_get_contents("http://0.0.0.0:5056/signup");
    echo $xmlr;
?>
<html>
    <head>
        <title>
            Upload format
        </title>
    </head>
    <body>
        <pre>


            Each service will be a folder with name service-<i>number</i>
            Numbering should be serially from 1,2,...
            Each folder can have files of supported formats only
            {.py, .json}

            Sample:

            service1
            |__________main.py
            |__________helper.py
            
            service2
            |__________main.py
            |__________helper.py

            config.json


            zip all these folders. And upload the zip. Only zip compression is allowed.
            
        </pre>

    </body>
</html>
