<html>
    <head>
        <title>
            Is this soln
        </title>
    </head>
    <body>

        <div class='updatable'></div> 
       
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
        <script>
         $(document).ready(function(){ //wait until page is ready
                localStorage.setItem("username","gaurav");
         })
        </script>
       </body>
</html>